namespace UltraBend.ViewForms
{
    partial class StudyView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn6 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn7 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn8 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn9 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn10 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn11 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn12 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            this.radGridViewStudy = new Telerik.WinControls.UI.RadGridView();
            this.caseBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewStudy)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewStudy.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.caseBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // radGridViewStudy
            // 
            this.radGridViewStudy.BackColor = System.Drawing.SystemColors.Control;
            this.radGridViewStudy.Cursor = System.Windows.Forms.Cursors.Default;
            this.radGridViewStudy.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radGridViewStudy.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.radGridViewStudy.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radGridViewStudy.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.radGridViewStudy.Location = new System.Drawing.Point(0, 0);
            // 
            // 
            // 
            this.radGridViewStudy.MasterTemplate.AddNewRowPosition = Telerik.WinControls.UI.SystemRowPosition.Bottom;
            this.radGridViewStudy.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewTextBoxColumn1.DataType = typeof(System.Guid);
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "Id";
            gridViewTextBoxColumn1.HeaderText = "Id";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.IsVisible = false;
            gridViewTextBoxColumn1.Name = "Id";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.Width = 56;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "Name";
            gridViewTextBoxColumn2.HeaderText = "Name";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "Name";
            gridViewTextBoxColumn2.Width = 126;
            gridViewTextBoxColumn3.DataType = typeof(System.Nullable<System.Guid>);
            gridViewTextBoxColumn3.EnableExpressionEditor = false;
            gridViewTextBoxColumn3.FieldName = "StudyId";
            gridViewTextBoxColumn3.HeaderText = "Study";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.IsVisible = false;
            gridViewTextBoxColumn3.Name = "StudyId";
            gridViewTextBoxColumn3.Width = 69;
            gridViewTextBoxColumn4.DataType = typeof(System.Nullable<System.Guid>);
            gridViewTextBoxColumn4.EnableExpressionEditor = false;
            gridViewTextBoxColumn4.FieldName = "DesignId";
            gridViewTextBoxColumn4.HeaderText = "Design";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.IsVisible = false;
            gridViewTextBoxColumn4.Name = "DesignId";
            gridViewTextBoxColumn4.Width = 78;
            gridViewTextBoxColumn5.DataType = typeof(System.Nullable<double>);
            gridViewTextBoxColumn5.EnableExpressionEditor = false;
            gridViewTextBoxColumn5.FieldName = "DeflectionAngle";
            gridViewTextBoxColumn5.HeaderText = "DeflectionAngle";
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.Name = "DeflectionAngle";
            gridViewTextBoxColumn5.Width = 126;
            gridViewTextBoxColumn6.DataType = typeof(System.Nullable<double>);
            gridViewTextBoxColumn6.EnableExpressionEditor = false;
            gridViewTextBoxColumn6.FieldName = "UmbilicalTension";
            gridViewTextBoxColumn6.HeaderText = "UmbilicalTension";
            gridViewTextBoxColumn6.IsAutoGenerated = true;
            gridViewTextBoxColumn6.Name = "UmbilicalTension";
            gridViewTextBoxColumn6.Width = 126;
            gridViewTextBoxColumn7.DataType = typeof(System.Nullable<double>);
            gridViewTextBoxColumn7.EnableExpressionEditor = false;
            gridViewTextBoxColumn7.FieldName = "Temperature";
            gridViewTextBoxColumn7.HeaderText = "Temperature";
            gridViewTextBoxColumn7.IsAutoGenerated = true;
            gridViewTextBoxColumn7.Name = "Temperature";
            gridViewTextBoxColumn7.Width = 127;
            gridViewTextBoxColumn8.DataType = typeof(System.Nullable<System.Guid>);
            gridViewTextBoxColumn8.EnableExpressionEditor = false;
            gridViewTextBoxColumn8.FieldName = "ResultId";
            gridViewTextBoxColumn8.HeaderText = "Result";
            gridViewTextBoxColumn8.IsAutoGenerated = true;
            gridViewTextBoxColumn8.IsVisible = false;
            gridViewTextBoxColumn8.Name = "ResultId";
            gridViewTextBoxColumn8.Width = 40;
            gridViewTextBoxColumn9.DataType = typeof(System.Nullable<double>);
            gridViewTextBoxColumn9.EnableExpressionEditor = false;
            gridViewTextBoxColumn9.FieldName = "BSMomentAtRootEnd";
            gridViewTextBoxColumn9.HeaderText = "Moment root end";
            gridViewTextBoxColumn9.Name = "BSMomentAtRootEnd";
            gridViewTextBoxColumn9.ReadOnly = true;
            gridViewTextBoxColumn9.Width = 43;
            gridViewTextBoxColumn10.EnableExpressionEditor = false;
            gridViewTextBoxColumn10.FieldName = "BSShearForceAtRootEnd";
            gridViewTextBoxColumn10.HeaderText = "Shear force root end";
            gridViewTextBoxColumn10.Name = "BSShearForceAtRootEnd";
            gridViewTextBoxColumn10.ReadOnly = true;
            gridViewTextBoxColumn10.Width = 45;
            gridViewTextBoxColumn11.EnableExpressionEditor = false;
            gridViewTextBoxColumn11.FieldName = "RiserTensionAtRootEnd";
            gridViewTextBoxColumn11.HeaderText = "Tension root end";
            gridViewTextBoxColumn11.Name = "RiserTensionAtRootEnd";
            gridViewTextBoxColumn11.ReadOnly = true;
            gridViewTextBoxColumn11.Width = 51;
            gridViewTextBoxColumn12.EnableExpressionEditor = false;
            gridViewTextBoxColumn12.FieldName = "MaximumCurvature";
            gridViewTextBoxColumn12.HeaderText = "Maximum curvature";
            gridViewTextBoxColumn12.Name = "MaximumCurvature";
            gridViewTextBoxColumn12.ReadOnly = true;
            gridViewTextBoxColumn12.Width = 55;
            this.radGridViewStudy.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewTextBoxColumn5,
            gridViewTextBoxColumn6,
            gridViewTextBoxColumn7,
            gridViewTextBoxColumn8,
            gridViewTextBoxColumn9,
            gridViewTextBoxColumn10,
            gridViewTextBoxColumn11,
            gridViewTextBoxColumn12});
            this.radGridViewStudy.MasterTemplate.DataSource = this.caseBindingSource;
            this.radGridViewStudy.MasterTemplate.ShowFilteringRow = false;
            this.radGridViewStudy.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.radGridViewStudy.Name = "radGridViewStudy";
            this.radGridViewStudy.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.radGridViewStudy.ShowGroupPanel = false;
            this.radGridViewStudy.Size = new System.Drawing.Size(713, 479);
            this.radGridViewStudy.TabIndex = 0;
            this.radGridViewStudy.EditorRequired += new Telerik.WinControls.UI.EditorRequiredEventHandler(this.radGridViewStudy_EditorRequired);
            this.radGridViewStudy.CellBeginEdit += new Telerik.WinControls.UI.GridViewCellCancelEventHandler(this.radGridViewStudy_CellBeginEdit);
            this.radGridViewStudy.CellEndEdit += new Telerik.WinControls.UI.GridViewCellEventHandler(this.radGridViewStudy_CellEndEdit);
            this.radGridViewStudy.RowsChanged += new Telerik.WinControls.UI.GridViewCollectionChangedEventHandler(this.radGridViewStudy_RowsChanged);
            this.radGridViewStudy.DefaultValuesNeeded += new Telerik.WinControls.UI.GridViewRowEventHandler(this.radGridViewStudy_DefaultValuesNeeded);
            // 
            // caseBindingSource
            // 
            this.caseBindingSource.DataSource = typeof(UltraBend.Services.DomainObjects.Case);
            this.caseBindingSource.CurrentChanged += new System.EventHandler(this.caseBindingSource_CurrentChanged);
            // 
            // StudyView
            // 
            this.Controls.Add(this.radGridViewStudy);
            this.Name = "StudyView";
            this.Size = new System.Drawing.Size(713, 479);
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewStudy.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewStudy)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.caseBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView radGridView1;
        private Telerik.WinControls.UI.RadGridView radGridViewStudy;
        private System.Windows.Forms.BindingSource caseBindingSource;
    }
}
