namespace UltraBend.ViewForms
{
    partial class LoadContourView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            Telerik.WinControls.UI.CartesianArea cartesianArea1 = new Telerik.WinControls.UI.CartesianArea();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.radGridViewLoadContour = new Telerik.WinControls.UI.RadGridView();
            this.radChartView1 = new Telerik.WinControls.UI.RadChartView();
            this.radPanel1 = new Telerik.WinControls.UI.RadPanel();
            this.radPanel2 = new Telerik.WinControls.UI.RadPanel();
            this.loadContourBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewLoadContour)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewLoadContour.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radChartView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radPanel1)).BeginInit();
            this.radPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.radPanel2)).BeginInit();
            this.radPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.loadContourBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.radPanel2);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.radPanel1);
            this.splitContainer1.Size = new System.Drawing.Size(876, 642);
            this.splitContainer1.SplitterDistance = 277;
            this.splitContainer1.TabIndex = 0;
            // 
            // radGridViewLoadContour
            // 
            this.radGridViewLoadContour.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radGridViewLoadContour.Location = new System.Drawing.Point(0, 0);
            // 
            // 
            // 
            this.radGridViewLoadContour.MasterTemplate.AddNewRowPosition = Telerik.WinControls.UI.SystemRowPosition.Bottom;
            this.radGridViewLoadContour.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewTextBoxColumn1.DataType = typeof(double);
            gridViewTextBoxColumn1.FieldName = "DeflectionAngle";
            gridViewTextBoxColumn1.HeaderText = "DeflectionAngle";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "DeflectionAngle";
            gridViewTextBoxColumn1.Width = 428;
            gridViewTextBoxColumn2.DataType = typeof(double);
            gridViewTextBoxColumn2.FieldName = "UmbilicalTension";
            gridViewTextBoxColumn2.HeaderText = "UmbilicalTension";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "UmbilicalTension";
            gridViewTextBoxColumn2.Width = 426;
            this.radGridViewLoadContour.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2});
            this.radGridViewLoadContour.MasterTemplate.DataSource = this.loadContourBindingSource;
            this.radGridViewLoadContour.MasterTemplate.ShowFilteringRow = false;
            this.radGridViewLoadContour.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.radGridViewLoadContour.Name = "radGridViewLoadContour";
            this.radGridViewLoadContour.ShowGroupPanel = false;
            this.radGridViewLoadContour.Size = new System.Drawing.Size(876, 277);
            this.radGridViewLoadContour.TabIndex = 0;
            this.radGridViewLoadContour.EditorRequired += new Telerik.WinControls.UI.EditorRequiredEventHandler(this.radGridViewLoadContour_EditorRequired);
            this.radGridViewLoadContour.RowsChanged += new Telerik.WinControls.UI.GridViewCollectionChangedEventHandler(this.radGridViewLoadContour_RowsChanged);
            // 
            // radChartView1
            // 
            this.radChartView1.AreaDesign = cartesianArea1;
            this.radChartView1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radChartView1.Location = new System.Drawing.Point(0, 0);
            this.radChartView1.Name = "radChartView1";
            this.radChartView1.ShowGrid = false;
            this.radChartView1.Size = new System.Drawing.Size(876, 361);
            this.radChartView1.TabIndex = 0;
            this.radChartView1.Title = "Capacity Curve";
            // 
            // radPanel1
            // 
            this.radPanel1.Controls.Add(this.radChartView1);
            this.radPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radPanel1.Location = new System.Drawing.Point(0, 0);
            this.radPanel1.Name = "radPanel1";
            this.radPanel1.Size = new System.Drawing.Size(876, 361);
            this.radPanel1.TabIndex = 1;
            // 
            // radPanel2
            // 
            this.radPanel2.Controls.Add(this.radGridViewLoadContour);
            this.radPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radPanel2.Location = new System.Drawing.Point(0, 0);
            this.radPanel2.Name = "radPanel2";
            this.radPanel2.Size = new System.Drawing.Size(876, 277);
            this.radPanel2.TabIndex = 1;
            // 
            // loadContourBindingSource
            // 
            this.loadContourBindingSource.DataSource = typeof(UltraBend.Models.LoadContourViewModelRowEntry);
            this.loadContourBindingSource.DataMemberChanged += new System.EventHandler(this.loadContourBindingSource_DataMemberChanged);
            // 
            // LoadContourView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.splitContainer1);
            this.Name = "LoadContourView";
            this.Size = new System.Drawing.Size(876, 642);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewLoadContour.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridViewLoadContour)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radChartView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radPanel1)).EndInit();
            this.radPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.radPanel2)).EndInit();
            this.radPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.loadContourBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SplitContainer splitContainer1;
        private Telerik.WinControls.UI.RadGridView radGridViewLoadContour;
        private System.Windows.Forms.BindingSource loadContourBindingSource;
        private Telerik.WinControls.UI.RadChartView radChartView1;
        private Telerik.WinControls.UI.RadPanel radPanel2;
        private Telerik.WinControls.UI.RadPanel radPanel1;
    }
}
